### ISSUE TITLE
Error while excuting cae.sh in ubuntu linux 22.04

### ISSUE THREAD

**Issue by jssrivathsa** [calculix/cae#32]
getting the following error, kindly help

Traceback (most recent call last):
  File "/home/ccx/cae/src/cae.py", line 39, in <module>
    import checks
  File "/home/ccx/cae/src/checks.py", line 30, in <module>
    class Checks:
  File "/home/ccx/cae/src/checks.py", line 33, in Checks
    modules = subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ccx/cae/bin/python/bin/python3'

**Comment by imirzov** [comment]
Hi! Did you make all files in "/home/ccx/cae/" executable?
https://github.com/calculix/cae#how-to-use

**Comment by jssrivathsa** [comment]
Yes, all files in /home/ccx/cae/
I exactly followed the instructions, but I got this error.
OS is ubuntu 22.04 LTS, Python 3.10

**Comment by imirzov** [comment]
Then I'm sorry, I have no idea how to solve it. Leaving this issue opened.
